server:
  port: 9091

spring:
  application:
    name: MONEY-OBJECT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://discovery:8761/eureka/"
  instance:
    hostname: localhost

